src/LogCentre/LogCentre.Web/Areas/Admin/Models/LogSourceViewModel.cs
using LogCentre.Model;

using Microsoft.AspNetCore.Mvc.Rendering;

using System.ComponentModel.DataAnnotations;

namespace LogCentre.Web.Areas.Admin.Models
{
    public class LogSourceViewModel
    {
        public long Id { get; set; }

        [Required]
        public long HostId { get; set; }

        [Required]
        public long ProviderId { get; set; }

        [Required]
        [StringLength(ModelLiterals.NameLength)]
        [MaxLength(ModelLiterals.NameLength)]
        public string Name { get; set; } = string.Empty;

        [Required]
        [StringLength(ModelLiterals.PathLength)]
        [MaxLength(ModelLiterals.PathLength)]
        public string Path { get; set; } = string.Empty;

        [Required]
        [StringLength(ModelLiterals.FlagLength)]
        [MaxLength(ModelLiterals.FlagLength)]
        public string Active { get; set; } = ModelLiterals.Yes;

        [Required]
        [StringLength(ModelLiterals.FlagLength)]
        [MaxLength(ModelLiterals.FlagLength)]
        public string Deleted { get; set; } = ModelLiterals.No;

        public HostModel? Host { get; set; }
        public ProviderModel? Provider { get; set; }

        public SelectList HostSelectList { get; set; } = new SelectList(new List<string>());

        public SelectList ProviderSelectList { get; set; } = new SelectList(new List<string>());

        public override string ToString()
        {
            return $"Id[{Id}], HostId[{HostId}], ProviderId[{ProviderId}], Name[{Name}], Path[{Path}], Active[{Active}], Deleted:[{Deleted}], {base.ToString()}";
        }
    }
}

src/LogCentre/LogCentre.Web/Areas/Admin/Pages/LogSource/Index.cshtml.cs
using LogCentre.ApiClient;
using LogCentre.Model;
using LogCentre.Web.Models;
using LogCentre.Web.Services;

using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using LogCentre.Web.Helpers;
using LogCentre.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LogCentre.Web.Areas.Admin.Pages.LogSource
{
    public class IndexModel : PageModelBase<IndexModel>
    {
        public IndexModel(ILogger<IndexModel> logger,
            ILogCentreApiClient client,
            IRazorRenderService renderService,
            IConfiguration configuration)
            : base(logger, client, renderService, configuration)
        {
            LogSources = new List<LogSourceModel>();
        }

        public IEnumerable<LogSourceModel> LogSources { get; set; }

        public void OnGet()
        {
            Logger.LogDebug("OnGet()");
        }

        public async Task<PartialViewResult> OnGetViewAllPartialAsync()
        {
            Logger.LogDebug("OnGetViewAllPartialAsync()");
            var stopwatch = Stopwatch.StartNew();

            try
            {
                var response = await ApiClient.GetLogSourcesAsync();
                response = response.Where(x => x.Active == ModelLiterals.Yes && x.Deleted == ModelLiterals.No).ToList();
                LogSources = response;

                return new PartialViewResult
                {
                    ViewName = "_ViewAll",
                    ViewData = new ViewDataDictionary<IEnumerable<LogSourceModel>>(ViewData, LogSources)
                };
            }
            catch (Exception ex)
            {
                Logger.LogError($"ONGetViewAllPartialAsync() | Error [{ex}]", ex);
                throw;
            }
            finally
            {
                stopwatch.Stop();
                Logger.LogInformation("*** OnGetViewAllPartialAsync took [{0}]", stopwatch.Elapsed);
            }
        }

        public async Task<JsonResult> OnGetCreateOrEditAsync(long id = 0)
        {
            Logger.LogDebug("OnGetCreateOrEditAsync() | id [{0}]", id);
            var stopwatch = Stopwatch.StartNew();

            try
            {
                var hostSelectList = await GetHostsSelectListAsync();
                var providerSelectList = await GetProvidersSelectListAsync();
                LogSourceModel model;
                if (id == 0)
                {
                    model = new LogSourceModel();
                }
                else
                {
                    model = await ApiClient.GetLogSourceByIdAsync(id);
                    if (model == null)
                    {
                        model = new LogSourceModel();
                    }
                }

                var viewModel = new LogSourceViewModel
                {
                    Id = model.Id,
                    HostId = model.HostId,
                    ProviderId = model.ProviderId,
                    Name = model.Name,
                    Path = model.Path,
                    Host = model.Host,
                    Provider = model.Provider
                };

                viewModel.HostSelectList = hostSelectList;
                viewModel.ProviderSelectList = providerSelectList;
                return new JsonResult(new { isValid = true, html = await RenderService.ToStringAsync("_CreateOrEdit", viewModel) });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, $"OnGetCreateOrEditAsync() error [{ex}]");
                return new JsonResult(new { isValid = false, html = await RenderService.ToStringAsync("_CreateOrEdit", new LogSourceViewModel()), errors = ex.Message });
            }
            finally
            {
                stopwatch.Stop();
                Logger.LogInformation("*** OnGetCreateOrEditAsync took [{0}]", stopwatch.Elapsed);
            }
        }

        public async Task<JsonResult> OnPostCreateOrEditAsync(long id, [Bind("HostId,ProviderId,Name,Path,Active,Deleted,Id")] LogSourceViewModel logSource)
        {
            Logger.LogDebug("OnPostCreateOrEditAsync() | id [{0}], logSource [{1}]", id, logSource);
            var stopwatch = Stopwatch.StartNew();

            try
            {
                ValidateLogSource(id, logSource);
                if (ModelState.IsValid)
                {
                    var logSourceModel = new LogSourceModel
                    {
                        Id = logSource.Id,
                        HostId = logSource.HostId,
                        ProviderId = logSource.ProviderId,
                        Name = logSource.Name,
                        Path = logSource.Path,
                        Active = logSource.Active,
                        Deleted = logSource.Deleted
                    };

                    if (id == 0)
                    {
                        try
                        {
                            var response = await ApiClient.CreateLogSourceAsync(logSourceModel);
                        }
                        catch (Exception ex)
                        {
                            Logger.LogError($"OnPostCreateOrEditAsync() | creating new logSource error[{ex}]", ex);
                            var html = await RenderService.ToStringAsync("_CreateOrEdit", logSource);
                            return new JsonResult(new { isValid = false, html = html, errors = ex.Message });
                        }
                    }
                    else
                    {
                        try
                        {
                            await ApiClient.UpdateLogSourceAsync(logSourceModel);
                        }
                        catch (Exception ex)
                        {
                            Logger.LogError($"OnPostCreateOrEditAsync() | editing logSource error[{ex}]", ex);
                            var html = await RenderService.ToStringAsync("_CreateOrEdit", logSource);
                            return new JsonResult(new { isValid = false, html = html, errors = ex.Message });
                        }
                    }

                    return await LoadAsync();
                }
                else
                {
                    var hostSelectList = await GetHostsSelectListAsync(logSource.HostId);
                    var providerSelectList = await GetProvidersSelectListAsync(logSource.ProviderId);
                    logSource.HostSelectList = hostSelectList;
                    logSource.ProviderSelectList = providerSelectList;
                    var modelStateErrors = ModelStateHelper.GetModelStateErrors(ModelState);
                    var html = await RenderService.ToStringAsync("_CreateOrEdit", logSource);
                    return new JsonResult(new { isValid = false, html = html, errors = modelStateErrors });
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, $"OnPostCreateOrEditAsync() error [{ex}]");
                return new JsonResult(new { isValid = false, html = await RenderService.ToStringAsync("_CreateOrEdit", logSource) });
            }
            finally
            {
                stopwatch.Stop();
                Logger.LogInformation("*** OnPostCreateOrEditAsync took [{0}]", stopwatch.Elapsed);
            }
        }

        public async Task<JsonResult> OnPostDeleteAsync(long id)
        {
            Logger.LogDebug("OnPostDeleteAsync() | id [{0}]", id);
            var stopwatch = Stopwatch.StartNew();

            try
            {
                await ApiClient.DeleteLogSourceAsync(id);
                return await LoadAsync();
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, $"OnPostDeleteAsync() error [{ex}]");
                return await LoadAsync(false, ex.Message);
            }
            finally
            {
                stopwatch.Stop();
                Logger.LogInformation("*** OnPostDeleteAsync took [{0}]", stopwatch.Elapsed);
            }
        }

        private async Task<JsonResult> LoadAsync(bool isValid = true, string message = "")
        {
            Logger.LogDebug("LoadAsync() | isValid[{isValid}], message[{message}]", isValid, message);
            var html = string.Empty;

            try
            {
                var response = await ApiClient.GetLogSourcesAsync();
                response = response.Where(x => x.Active == ModelLiterals.Yes && x.Deleted == ModelLiterals.No).ToList();
                LogSources = response;
                html = await RenderService.ToStringAsync("_ViewAll", LogSources);
                return new JsonResult(new { isValid = isValid, message = message, html = html });
            }
            catch (Exception ex)
            {
                html = await RenderService.ToStringAsync("_ViewAll", LogSources);
                return new JsonResult(new { isValid = false, message = ex.Message, html = html });
            }
        }

        private async Task<SelectList> GetHostsSelectListAsync(long? selectedId = null)
        {
            Logger.LogDebug("GetHostSelectListAsync() | selectedId[{selectedId}]", selectedId);
            var items = await ApiClient.GetHostsAsync();
            items = items.Where(x => x.Active == ModelLiterals.Yes && x.Deleted == ModelLiterals.No).ToList();
            var list = new SelectList(items, "Id", "Name", selectedId);
            return list;
        }

        private async Task<SelectList> GetProvidersSelectListAsync(long? selectedId = null)
        {
            Logger.LogDebug("GetProvidersSelectListAsync() | selectedId[{selectedId}]", selectedId);
            var items = await ApiClient.GetProvidersAsync();
            items = items.Where(x => x.Active == ModelLiterals.Yes && x.Deleted == ModelLiterals.No).ToList();
            var list = new SelectList(items, "Id", "Name", selectedId);

src/LogCentre/LogCentre.Web/Areas/Admin/Pages/LogSource/Index.cshtml
@page
@model LogCentre.Web.Areas.Admin.Pages.LogSource.IndexModel
@{
    ViewData["Title"] = "Log Sources";
    Layout = "/Pages/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="col-sm-12" style="padding: 20px">
        <a onclick="jQueryModalGet('?handler=CreateOrEdit','Create Log Source')" class="btn bg-success">
            Create
        </a>
        <a id="reload" class="btn bg-warning">
            Reload
        </a>
    </div>
    <div id="viewAll" class="card-body"></div>
</div>
@section Scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            loadData();

            $('#reload').on('click', function () {
                loadData();
            });
        });

        function loadData() {
            window.console.log('loadData()');
            $('#viewAll').empty().html('<div><div class="spinner-border text-dark" role="status"><span class="sr-only"></span></div>Loading...</div>');
            $('#viewAll').load('?handler=ViewAllPartial');
        }
    </script>
}

src/LogCentre/LogCentre.Web/Areas/Admin/Pages/LogSource/_CreateOrEdit.cshtml
@using LogCentre.Model
@using LogCentre.Web.Areas.Admin.Models

@model LogSourceViewModel

<div id="notifications"></div>
<form id="create-form" method="post" asp-page="Index" asp-route-id="@Model.Id" asp-page-handler="CreateOrEdit" onsubmit="return jQueryModalPost(this);">
    @if (Model.Id > 0)
    {
        <div class="mb-3 row">
            <label for="staticId" class="col-sm-2 col-form-label">Id</label>
            <div class="col-sm-10">
                <input type="text" readonly class="form-control-plaintext" id="staticId" value="@Model.Id">
            </div>
        </div>
    }

    <div class="mb-3 row">
        <label class="col-sm-2 form-label">Host</label>
        <div class="col-md-10">
            <select asp-for="HostId" class="form-control" asp-items="Model.HostSelectList">
                <option>Select Host</option>
            </select>
            <span asp-validation-for="HostId" class="text-danger"></span>
        </div>
    </div>

    <div class="mb-3 row">
        <label class="col-sm-2 form-label">Provider</label>
        <div class="col-md-10">
            <select asp-for="ProviderId" class="form-control" asp-items="Model.ProviderSelectList">
                <option>Select Provider</option>
            </select>
            <span asp-validation-for="ProviderId" class="text-danger"></span>
        </div>
    </div>

    <div class="mb-3 row">
        <label class="col-sm-2 form-label">Name</label>
        <div class="col-md-10">
            <input autocomplete="off" asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="mb-3 row">
        <label class="col-sm-2 form-label">Path</label>
        <div class="col-md-10">
            <input autocomplete="off" asp-for="Path" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>

    <div class="mb-3 row d-none">
        <label class="col-sm-2 form-label">Active</label>
        <div class="col-md-10">
            <select asp-for="Active" class="form-control">
                <option>Active</option>
                @if (Model.Active == ModelLiterals.Yes)
                {
                    <option value="@ModelLiterals.Yes" selected>@ModelLiterals.Yes</option>
                    <option value="@ModelLiterals.No">@ModelLiterals.No</option>
                }
                else
                {
                    <option value="@ModelLiterals.Yes">@ModelLiterals.Yes</option>
                    <option value="@ModelLiterals.No" selected>@ModelLiterals.No</option>
                }
            </select>
        </div>
    </div>

    <div class="mb-3 row d-none">
        <label class="col-sm-2 form-label">Deleted</label>
        <div class="col-md-10">
            <select asp-for="Deleted" class="form-control">
                <option>Deleted</option>
                @if (Model.Deleted == ModelLiterals.Yes)
                {
                    <option value="@ModelLiterals.Yes" selected>@ModelLiterals.Yes</option>
                    <option value="@ModelLiterals.No">@ModelLiterals.No</option>
                }
                else
                {
                    <option value="@ModelLiterals.Yes">@ModelLiterals.Yes</option>
                    <option value="@ModelLiterals.No" selected>@ModelLiterals.No</option>
                }
            </select>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
        </div>
    </div>

    <div class="form-group justify-content-between">
        <button type="button" class="btn btn-secondary close-button" data-bs-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary save-button">Save</button>
    </div>
</form>

<script type="text/javascript" language=javascript>
    $.validator.unobtrusive.parse(document);
</script>

src/LogCentre/LogCentre.Web/Areas/Admin/Pages/LogSource/_ViewAll.cshtml
@using LogCentre.Model

@model IEnumerable<LogSourceModel>

<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover" id="logSourceTable">
        <caption>List of Log Sources</caption>
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Host
                </th>
                <th>
                    Provider
                </th>
                <th>
                    Name
                </th>
                <th>
                    Path
                </th>
                <th class="d-none">
                    Active
                </th>
                <th class="d-none">
                    Deleted
                </th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                @foreach (var logSource in Model)
                {
                    <tr>
                        <td>
                            @logSource.Id
                        </td>
                        <td>
                            @logSource.Host?.Name
                        </td>
                        <td>
                            @logSource.Provider?.Name
                        </td>
                        <td>
                            @logSource.Name
                        </td>
                        <td>
                            @logSource.Path
                        </td>
                        <td class="d-none">
                            @logSource.Active
                        </td>
                        <td class="d-none">
                            @logSource.Deleted
                        </td>
                        <td class="text-right">
                            <a onclick="jQueryModalGet('?handler=CreateOrEdit&id=@logSource.Id', 'Edit Log Source')" class="btn btn-info text-white">Edit</a>
                            <form method="post" asp-page="Index" asp-route-id="@logSource.Id" asp-page-handler="Delete" onsubmit="return jQueryModalDelete(this)" class="d-inline">
                                <button type="submit" class="btn btn-danger text-white">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        var table = $('#logSourceTable').DataTable({
            "order": [[1, 'asc']]
        });

        $('#logSourceTable tbody')
            .on('mouseenter', 'td', function () {
                var colIdx = table.cell(this).index();
                if (colIdx) {
                    var col = colIdx.column;
                    if (col) {
                        $(table.cells().nodes()).removeClass('highlight');
                        $(table.column(col).nodes()).addClass('highlight');
                    }
                }
            });
    });
</script>